# Generated by Django 4.1.3 on 2023-06-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('flight_name', models.CharField(max_length=100)),
                ('departure_point', models.CharField(max_length=4)),
                ('arrival_point', models.CharField(max_length=4)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('seats_booked', models.PositiveIntegerField()),
                ('max_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_reference', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A2Core.customer')),
                ('flight', models.ManyToManyField(to='A2Core.flight')),
            ],
        ),
    ]
